// TODO: GENERATED BY AI, Check, fix if need and remake.

package net.tokishu.util.helper;

import net.tokishu.ObsidianGate;
import org.bukkit.configuration.file.FileConfiguration;
import java.sql.*;

public class DataBase {

    private static DataBase instance;
    private Connection connection;
    private String dbType;
    private String host, database, user, password, prefix;
    private int port;
    private String sqlitePath;

    private DataBase() {
        FileConfiguration config = ObsidianGate.getPluginConfig();

        this.dbType = config.getString("database.type", "mysql");
        this.host = config.getString("database.host", "localhost");
        this.port = config.getInt("database.port", 3306);
        this.database = config.getString("database.name", "obsidiangate");
        this.user = config.getString("database.user", "root");
        this.password = config.getString("database.password", "password");
        this.prefix = config.getString("database.prefix", "OG_");
        this.sqlitePath = config.getString("database.sqlite-path", "obsidiangate.db");

        setupDB();  // Инициализируем БД
    }

    // Получаем инстанс DataBase
    public static DataBase getInstance() {
        if (instance == null) {
            instance = new DataBase();
        }
        return instance;
    }

    // Инициализация и подключение к БД
    private void setupDB() {
        try {
            if ("mysql".equalsIgnoreCase(dbType) || "postgres".equalsIgnoreCase(dbType)) {
                String url = "jdbc:" + dbType + "://" + host + ":" + port + "/" + database;
                connection = DriverManager.getConnection(url, user, password);
            } else if ("sqlite".equalsIgnoreCase(dbType)) {
                connection = DriverManager.getConnection("jdbc:sqlite:" + sqlitePath);
            }
            createTablesIfNeeded();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Метод для создания таблиц, если их нет
    private void createTablesIfNeeded() {
        try (Statement stmt = connection.createStatement()) {
            if ("mysql".equalsIgnoreCase(dbType) || "postgres".equalsIgnoreCase(dbType)) {
                String query = "CREATE TABLE IF NOT EXISTS " + prefix + "linked_accounts (" +
                        "uuid VARCHAR(36) PRIMARY KEY," +
                        "discord_id VARCHAR(36) NOT NULL" +
                        ");";
                stmt.executeUpdate(query);
            } else if ("sqlite".equalsIgnoreCase(dbType)) {
                String query = "CREATE TABLE IF NOT EXISTS " + prefix + "linked_accounts (" +
                        "uuid TEXT PRIMARY KEY," +
                        "discord_id TEXT NOT NULL" +
                        ");";
                stmt.executeUpdate(query);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Приватный метод для получения данных
    private ResultSet getData(String sql, Object... params) throws SQLException {
        PreparedStatement stmt = connection.prepareStatement(sql);
        for (int i = 0; i < params.length; i++) {
            stmt.setObject(i + 1, params[i]);
        }
        return stmt.executeQuery();
    }

    // Приватный метод для отправки данных в БД
    private void sendData(String sql, Object... params) throws SQLException {
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            for (int i = 0; i < params.length; i++) {
                stmt.setObject(i + 1, params[i]);
            }
            stmt.executeUpdate();
        }
    }

    // Метод для получения линка игрока
    public String getLinkedDiscordId(String uuid) {
        try {
            ResultSet rs = getData("SELECT discord_id FROM " + prefix + "linked_accounts WHERE uuid = ?", uuid);
            if (rs.next()) {
                return rs.getString("discord_id");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    // Метод для создания линка между игроком и Discord ID
    public void linkPlayerToDiscord(String uuid, String discordId) {
        try {
            sendData("INSERT INTO " + prefix + "linked_accounts (uuid, discord_id) VALUES (?, ?)", uuid, discordId);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Метод для проверки, связан ли игрок с Discord
    public boolean isPlayerLinked(String uuid) {
        try {
            ResultSet rs = getData("SELECT discord_id FROM " + prefix + "linked_accounts WHERE uuid = ?", uuid);
            return rs.next();  // Если запись найдена, значит игрок связан с Discord
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }

    // Закрытие соединения с БД
    public void close() {
        try {
            if (connection != null && !connection.isClosed()) {
                connection.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
